name: enqueue-pr-test
on:
  # When a PR is approved, add the queue label
  pull_request_review:
    types: [submitted]

jobs:
  enqueue:
    if: github.event.pull_request.base.ref == 'master'
    # && contains(github.event.pull_request.reviews.*.state, 'APPROVED')
    name: dequeue
    runs-on: ubuntu-20.04
    steps:
      - name: Extract info
        id: infos
        run: echo ${{ toJson(github) }}
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: pr-test-queue
